version: "3.8"

services:
  db:
    container_name: db_container
    image: postgres:latest
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  gces_back:
    container_name: api_service
    build: .
    restart: always
    environment:
      DB_NAME: myproject
      DB_USER: myuser
      DB_PASS: password
    command: sh docker-entrypoint.sh
    volumes:
      - .:/usr/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
    driver: local

networks:
  task-service:
    external:
      name: task-service